//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asl.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="aslParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IaslListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.constantTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantTest([NotNull] aslParser.ConstantTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.constantTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantTest([NotNull] aslParser.ConstantTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.expressionTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionTest([NotNull] aslParser.ExpressionTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.expressionTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionTest([NotNull] aslParser.ExpressionTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.lineTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineTest([NotNull] aslParser.LineTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.lineTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineTest([NotNull] aslParser.LineTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSourceFile([NotNull] aslParser.SourceFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSourceFile([NotNull] aslParser.SourceFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.lValueSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLValueSet([NotNull] aslParser.LValueSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.lValueSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLValueSet([NotNull] aslParser.LValueSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] aslParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] aslParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.referenceTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReferenceTag([NotNull] aslParser.ReferenceTagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.referenceTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReferenceTag([NotNull] aslParser.ReferenceTagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] aslParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] aslParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.linedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinedExpression([NotNull] aslParser.LinedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.linedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinedExpression([NotNull] aslParser.LinedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssertStatement([NotNull] aslParser.AssertStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssertStatement([NotNull] aslParser.AssertStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.controlFlowStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlFlowStatements([NotNull] aslParser.ControlFlowStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.controlFlowStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlFlowStatements([NotNull] aslParser.ControlFlowStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.hardStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHardStatements([NotNull] aslParser.HardStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.hardStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHardStatements([NotNull] aslParser.HardStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.enumerationDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationDeclaration([NotNull] aslParser.EnumerationDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.enumerationDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationDeclaration([NotNull] aslParser.EnumerationDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeMember([NotNull] aslParser.TypeMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeMember([NotNull] aslParser.TypeMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.typeArrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArrayDeclaration([NotNull] aslParser.TypeArrayDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.typeArrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArrayDeclaration([NotNull] aslParser.TypeArrayDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] aslParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] aslParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.emptyTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyTypeDeclaration([NotNull] aslParser.EmptyTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.emptyTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyTypeDeclaration([NotNull] aslParser.EmptyTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.newTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewTypeDeclaration([NotNull] aslParser.NewTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.newTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewTypeDeclaration([NotNull] aslParser.NewTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.oldTypeRedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOldTypeRedeclaration([NotNull] aslParser.OldTypeRedeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.oldTypeRedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOldTypeRedeclaration([NotNull] aslParser.OldTypeRedeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] aslParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] aslParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] aslParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] aslParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.whenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenStatement([NotNull] aslParser.WhenStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.whenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenStatement([NotNull] aslParser.WhenStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] aslParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] aslParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] aslParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] aslParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStatement([NotNull] aslParser.ElseIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStatement([NotNull] aslParser.ElseIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] aslParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] aslParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] aslParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] aslParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.explicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitFunctionDeclaration([NotNull] aslParser.ExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.explicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitFunctionDeclaration([NotNull] aslParser.ExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.singleVariableFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleVariableFunction([NotNull] aslParser.SingleVariableFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.singleVariableFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleVariableFunction([NotNull] aslParser.SingleVariableFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.setExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExplicitFunctionDeclaration([NotNull] aslParser.SetExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.setExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExplicitFunctionDeclaration([NotNull] aslParser.SetExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.instructionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionDeclaration([NotNull] aslParser.InstructionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.instructionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionDeclaration([NotNull] aslParser.InstructionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.operandData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperandData([NotNull] aslParser.OperandDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.operandData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperandData([NotNull] aslParser.OperandDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.instructionHelperData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionHelperData([NotNull] aslParser.InstructionHelperDataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.instructionHelperData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionHelperData([NotNull] aslParser.InstructionHelperDataContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.normalExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalExplicitFunctionDeclaration([NotNull] aslParser.NormalExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.normalExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalExplicitFunctionDeclaration([NotNull] aslParser.NormalExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclaration([NotNull] aslParser.ArrayDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclaration([NotNull] aslParser.ArrayDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.commaSeperatedExpressionSingleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommaSeperatedExpressionSingleton([NotNull] aslParser.CommaSeperatedExpressionSingletonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.commaSeperatedExpressionSingleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommaSeperatedExpressionSingleton([NotNull] aslParser.CommaSeperatedExpressionSingletonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.commaSeperatedExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommaSeperatedExpressions([NotNull] aslParser.CommaSeperatedExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.commaSeperatedExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommaSeperatedExpressions([NotNull] aslParser.CommaSeperatedExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.functionArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionArguments([NotNull] aslParser.FunctionArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.functionArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionArguments([NotNull] aslParser.FunctionArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.parentheses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentheses([NotNull] aslParser.ParenthesesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.parentheses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentheses([NotNull] aslParser.ParenthesesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.edgeCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEdgeCases([NotNull] aslParser.EdgeCasesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.edgeCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEdgeCases([NotNull] aslParser.EdgeCasesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bitAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitAccessor([NotNull] aslParser.BitAccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bitAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitAccessor([NotNull] aslParser.BitAccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bitFeild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitFeild([NotNull] aslParser.BitFeildContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bitFeild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitFeild([NotNull] aslParser.BitFeildContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.structAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructAccessor([NotNull] aslParser.StructAccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.structAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructAccessor([NotNull] aslParser.StructAccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.partAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartAccessor([NotNull] aslParser.PartAccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.partAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartAccessor([NotNull] aslParser.PartAccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.baseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseExpression([NotNull] aslParser.BaseExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.baseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseExpression([NotNull] aslParser.BaseExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.identifierPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierPath([NotNull] aslParser.IdentifierPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.identifierPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierPath([NotNull] aslParser.IdentifierPathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.numberRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberRange([NotNull] aslParser.NumberRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.numberRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberRange([NotNull] aslParser.NumberRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.functionScriptOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionScriptOperations([NotNull] aslParser.FunctionScriptOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.functionScriptOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionScriptOperations([NotNull] aslParser.FunctionScriptOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.functionSubscriptStructAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSubscriptStructAccessor([NotNull] aslParser.FunctionSubscriptStructAccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.functionSubscriptStructAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSubscriptStructAccessor([NotNull] aslParser.FunctionSubscriptStructAccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.inCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInCollection([NotNull] aslParser.InCollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.inCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInCollection([NotNull] aslParser.InCollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.functionScriptingSecond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionScriptingSecond([NotNull] aslParser.FunctionScriptingSecondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.functionScriptingSecond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionScriptingSecond([NotNull] aslParser.FunctionScriptingSecondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.unaryOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperations([NotNull] aslParser.UnaryOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.unaryOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperations([NotNull] aslParser.UnaryOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.exponentialOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExponentialOperations([NotNull] aslParser.ExponentialOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.exponentialOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExponentialOperations([NotNull] aslParser.ExponentialOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.multiplicationOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationOperations([NotNull] aslParser.MultiplicationOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.multiplicationOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationOperations([NotNull] aslParser.MultiplicationOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.additionOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionOperations([NotNull] aslParser.AdditionOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.additionOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionOperations([NotNull] aslParser.AdditionOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.concatOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatOperations([NotNull] aslParser.ConcatOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.concatOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatOperations([NotNull] aslParser.ConcatOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.shiftingOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftingOperations([NotNull] aslParser.ShiftingOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.shiftingOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftingOperations([NotNull] aslParser.ShiftingOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.comparisonOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOperations([NotNull] aslParser.ComparisonOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.comparisonOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOperations([NotNull] aslParser.ComparisonOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.equalityOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityOperations([NotNull] aslParser.EqualityOperationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.equalityOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityOperations([NotNull] aslParser.EqualityOperationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bitwiseAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseAndOperation([NotNull] aslParser.BitwiseAndOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bitwiseAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseAndOperation([NotNull] aslParser.BitwiseAndOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bitwiseExclusiveOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseExclusiveOrOperation([NotNull] aslParser.BitwiseExclusiveOrOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bitwiseExclusiveOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseExclusiveOrOperation([NotNull] aslParser.BitwiseExclusiveOrOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bitwiseOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBitwiseOrOperation([NotNull] aslParser.BitwiseOrOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bitwiseOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBitwiseOrOperation([NotNull] aslParser.BitwiseOrOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.logicalAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndOperation([NotNull] aslParser.LogicalAndOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.logicalAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndOperation([NotNull] aslParser.LogicalAndOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.logicalOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrOperation([NotNull] aslParser.LogicalOrOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.logicalOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrOperation([NotNull] aslParser.LogicalOrOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.smallTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmallTernaryOperation([NotNull] aslParser.SmallTernaryOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.smallTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmallTernaryOperation([NotNull] aslParser.SmallTernaryOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bigTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBigTernaryOperation([NotNull] aslParser.BigTernaryOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bigTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBigTernaryOperation([NotNull] aslParser.BigTernaryOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.teranryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTeranryOperation([NotNull] aslParser.TeranryOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.teranryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTeranryOperation([NotNull] aslParser.TeranryOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] aslParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] aslParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.tupleSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleSingle([NotNull] aslParser.TupleSingleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.tupleSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleSingle([NotNull] aslParser.TupleSingleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple([NotNull] aslParser.TupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple([NotNull] aslParser.TupleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.bracketCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketCollection([NotNull] aslParser.BracketCollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.bracketCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketCollection([NotNull] aslParser.BracketCollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollection([NotNull] aslParser.CollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollection([NotNull] aslParser.CollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] aslParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] aslParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] aslParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] aslParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleType([NotNull] aslParser.TupleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleType([NotNull] aslParser.TupleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.constantType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantType([NotNull] aslParser.ConstantTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.constantType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantType([NotNull] aslParser.ConstantTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.concreteTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcreteTypes([NotNull] aslParser.ConcreteTypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.concreteTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcreteTypes([NotNull] aslParser.ConcreteTypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.dynamicTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDynamicTypes([NotNull] aslParser.DynamicTypesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.dynamicTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDynamicTypes([NotNull] aslParser.DynamicTypesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] aslParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] aslParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.binaryEncodingPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryEncodingPattern([NotNull] aslParser.BinaryEncodingPatternContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.binaryEncodingPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryEncodingPattern([NotNull] aslParser.BinaryEncodingPatternContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="aslParser.trueFalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrueFalse([NotNull] aslParser.TrueFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="aslParser.trueFalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrueFalse([NotNull] aslParser.TrueFalseContext context);
}
