//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from asl.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="aslParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IaslVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.constantTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantTest([NotNull] aslParser.ConstantTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.expressionTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionTest([NotNull] aslParser.ExpressionTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.lineTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineTest([NotNull] aslParser.LineTestContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.sourceFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSourceFile([NotNull] aslParser.SourceFileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.lValueSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLValueSet([NotNull] aslParser.LValueSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] aslParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.referenceTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceTag([NotNull] aslParser.ReferenceTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] aslParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.linedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinedExpression([NotNull] aslParser.LinedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.assertStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertStatement([NotNull] aslParser.AssertStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.controlFlowStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlFlowStatements([NotNull] aslParser.ControlFlowStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.hardStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHardStatements([NotNull] aslParser.HardStatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.enumerationDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationDeclaration([NotNull] aslParser.EnumerationDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.typeMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeMember([NotNull] aslParser.TypeMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.typeArrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeArrayDeclaration([NotNull] aslParser.TypeArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclaration([NotNull] aslParser.TypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.emptyTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyTypeDeclaration([NotNull] aslParser.EmptyTypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.newTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewTypeDeclaration([NotNull] aslParser.NewTypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.oldTypeRedeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOldTypeRedeclaration([NotNull] aslParser.OldTypeRedeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForLoop([NotNull] aslParser.ForLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStatement([NotNull] aslParser.CaseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.whenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhenStatement([NotNull] aslParser.WhenStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] aslParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] aslParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIfStatement([NotNull] aslParser.ElseIfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] aslParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] aslParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.explicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitFunctionDeclaration([NotNull] aslParser.ExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.singleVariableFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleVariableFunction([NotNull] aslParser.SingleVariableFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.setExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetExplicitFunctionDeclaration([NotNull] aslParser.SetExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.instructionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionDeclaration([NotNull] aslParser.InstructionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.operandData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperandData([NotNull] aslParser.OperandDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.instructionHelperData"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionHelperData([NotNull] aslParser.InstructionHelperDataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.normalExplicitFunctionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNormalExplicitFunctionDeclaration([NotNull] aslParser.NormalExplicitFunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] aslParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.commaSeperatedExpressionSingleton"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommaSeperatedExpressionSingleton([NotNull] aslParser.CommaSeperatedExpressionSingletonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.commaSeperatedExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommaSeperatedExpressions([NotNull] aslParser.CommaSeperatedExpressionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.functionArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionArguments([NotNull] aslParser.FunctionArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.parentheses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentheses([NotNull] aslParser.ParenthesesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.edgeCases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEdgeCases([NotNull] aslParser.EdgeCasesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bitAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitAccessor([NotNull] aslParser.BitAccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bitFeild"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitFeild([NotNull] aslParser.BitFeildContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.structAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructAccessor([NotNull] aslParser.StructAccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.partAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartAccessor([NotNull] aslParser.PartAccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.baseExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseExpression([NotNull] aslParser.BaseExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.identifierPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierPath([NotNull] aslParser.IdentifierPathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.numberRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberRange([NotNull] aslParser.NumberRangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.functionScriptOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScriptOperations([NotNull] aslParser.FunctionScriptOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.functionSubscriptStructAccessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSubscriptStructAccessor([NotNull] aslParser.FunctionSubscriptStructAccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.inCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInCollection([NotNull] aslParser.InCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.functionScriptingSecond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionScriptingSecond([NotNull] aslParser.FunctionScriptingSecondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.unaryOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperations([NotNull] aslParser.UnaryOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.exponentialOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExponentialOperations([NotNull] aslParser.ExponentialOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.multiplicationOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicationOperations([NotNull] aslParser.MultiplicationOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.additionOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditionOperations([NotNull] aslParser.AdditionOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.concatOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatOperations([NotNull] aslParser.ConcatOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.shiftingOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftingOperations([NotNull] aslParser.ShiftingOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.comparisonOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOperations([NotNull] aslParser.ComparisonOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.equalityOperations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityOperations([NotNull] aslParser.EqualityOperationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bitwiseAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseAndOperation([NotNull] aslParser.BitwiseAndOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bitwiseExclusiveOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseExclusiveOrOperation([NotNull] aslParser.BitwiseExclusiveOrOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bitwiseOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitwiseOrOperation([NotNull] aslParser.BitwiseOrOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.logicalAndOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndOperation([NotNull] aslParser.LogicalAndOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.logicalOrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrOperation([NotNull] aslParser.LogicalOrOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.smallTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSmallTernaryOperation([NotNull] aslParser.SmallTernaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bigTernaryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBigTernaryOperation([NotNull] aslParser.BigTernaryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.teranryOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTeranryOperation([NotNull] aslParser.TeranryOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] aslParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.tupleSingle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleSingle([NotNull] aslParser.TupleSingleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple([NotNull] aslParser.TupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.bracketCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracketCollection([NotNull] aslParser.BracketCollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.collection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollection([NotNull] aslParser.CollectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] aslParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] aslParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.tupleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTupleType([NotNull] aslParser.TupleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.constantType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantType([NotNull] aslParser.ConstantTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.concreteTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcreteTypes([NotNull] aslParser.ConcreteTypesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.dynamicTypes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicTypes([NotNull] aslParser.DynamicTypesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] aslParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.binaryEncodingPattern"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryEncodingPattern([NotNull] aslParser.BinaryEncodingPatternContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="aslParser.trueFalse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrueFalse([NotNull] aslParser.TrueFalseContext context);
}
